In [1]:
import numpy as np
import cv2

In [60]:
img_color = cv2.imread('images/colorballs.jpg')

In [135]:
img_out = img_color.copy()
# img_out = cv2.pyrDown(img_out)
img_gray = cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY)
# img_gray = cv2.pyrDown(img_gray)

원 찾기

In [136]:
circles = cv2.HoughCircles(img_gray, cv2.HOUGH_GRADIENT, 1, 100, \
              param1=250, param2 =10, minRadius=80, maxRadius =100)

for i in circles[0]:
    cv2.circle(img_out, (i[0],i[1]), i[2], (0,0,255),2)

In [137]:
cv2.imshow('color', img_out)
cv2.waitKey(0)
cv2.destroyAllWindows()

원 찾기 (pyrDown)

In [145]:
img_out = img_color.copy()
img_out = cv2.pyrDown(img_out)
img_gray = cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY)
img_gray = cv2.pyrDown(img_gray)

In [146]:
circles = cv2.HoughCircles(img_gray, cv2.HOUGH_GRADIENT, 1, 70, \
              param1=180, param2 =15, minRadius=30, maxRadius =55)

for i in circles[0]:
    cv2.circle(img_out, (i[0],i[1]), i[2], (0,0,255),2)

In [147]:
cv2.imshow('color', img_out)
cv2.waitKey(0)
cv2.destroyAllWindows()

골프공처리

In [317]:
img_color = cv2.imread('images/golfballs.jpg')

In [318]:
img_out = img_color.copy()
img_gray = cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY)
ret,img_gray = cv2.threshold(img_gray,190,255,cv2.THRESH_OTSU)
# cv2.imshow('img_gray', img_gray)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [319]:
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
img_gray = cv2.morphologyEx(img_gray,cv2.MORPH_OPEN,kernel,iterations=1)
# cv2.imshow('img_gray', img_gray)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [320]:
circles = cv2.HoughCircles(img_gray, cv2.HOUGH_GRADIENT, 1, 95, \
              param1=100, param2 =16, minRadius=51, maxRadius =95)

for i in circles[0]:
    cv2.circle(img_out, (i[0],i[1]), i[2], (0,0,255),2)

In [321]:
cv2.imshow('color', img_out)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [327]:
import numpy as np
import cv2

img_color = cv2.imread('images/golfballs.jpg')

img_out = img_color.copy()
img_gray = cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY)
ret, img_gray = cv2.threshold(img_gray, 200, 255, cv2.THRESH_OTSU)

kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3,3))
img_gray = cv2.morphologyEx(img_gray, cv2.MORPH_OPEN, kernel, 
                                                       iterations=1)

circles = cv2.HoughCircles(img_gray, cv2.HOUGH_GRADIENT, 1, 100, 
               param1=180, param2 =20, minRadius=50, maxRadius=95)

for i in circles[0]:
    cv2.circle(img_out, (i[0],i[1]), i[2], (0,0,255),2)

cv2.imshow('color', img_out)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [358]:
img_color = cv2.imread('images/colorballs.jpg')

In [359]:
number1 = np.ones_like(img_color) * 127
number2 = np.ones_like(img_color) * 2

In [348]:
img_add1 = cv2.add(img_color,number1)
img_out = img_add1
img_add2 = img_color+127
print(img_color[0][0])
print(img_add1[0][0])
print(img_add2[0][0])

[15 12  8]
[255 255 255]
[9 6 2]


In [335]:
img_sub = cv2.subtract(img_color,number1)
img_out = img_sub

In [349]:
img_mul = cv2.multiply(img_color,number2)
img_out = img_mul

In [351]:
img_div = cv2.divide(img_color,number2)
img_out = img_div

In [353]:
cv2.imshow('color', img_out)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [360]:
img_max = cv2.max(img_color, number1)
img_out = img_max

In [362]:
img_min = cv2.min(img_color, number1)
img_out = img_min

In [364]:
img_abs = cv2.absdiff(img_color, number1)
img_out = img_abs

In [377]:
img_comp = cv2.compare(img_color,number1, cv2.CMP_GT)
img_out = img_comp

In [378]:
cv2.imshow('color', img_out)
cv2.waitKey(0)
cv2.destroyAllWindows()