# Getting Started with pandas

In [1]:
import pandas as pd
import numpy as np
pd.__version__

'1.0.5'

In [3]:
from pandas import Series, DataFrame

## Introduction to pandas Data Structures

### Series
- Series는 일련의 객체를 담을수 있는 1차원 배열 같은 자료 구조

In [47]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [7]:
obj.index  # like range(4)

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
obj2['a']

-5

In [12]:
obj2['d'] = 6
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [14]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [13]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [32]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [15]:
obj2_e = np.exp(obj2)
obj2_e

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [13]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [20]:
'b' in obj2

True

In [19]:
'e' in obj2

False

In [17]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [18]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [17]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [18]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [21]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [19]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [20]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [23]:
# 값을 더함 값이 없으면 NaN
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [24]:
obj4.name = 'population'
obj4.name

'population'

In [32]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [48]:
obj
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

#### 요소추가 / 요소삭제

In [51]:
obj = obj.append(pd.Series([5],index=['Tom']))
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
Tom      5
dtype: int64

In [54]:
obj = obj.drop('Tom')
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

#### 필터링

In [56]:
obj[obj >= 0][obj <=  5]

Bob     4
Ryan    3
dtype: int64

#### 정렬

In [60]:
obj.sort_index(ascending = False)

Steve    7
Ryan     3
Jeff    -5
Bob      4
dtype: int64

In [61]:
obj.sort_index(ascending = True) #ascending = True : 생략가능

Bob      4
Jeff    -5
Ryan     3
Steve    7
dtype: int64

In [66]:
obj.sort_values(ascending = True) #ascending = True : 생략가능

Jeff    -5
Ryan     3
Bob      4
Steve    7
dtype: int64

In [62]:
obj.sort_values(ascending = False)

Steve    7
Bob      4
Ryan     3
Jeff    -5
dtype: int64

### DataFrame

In [150]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [151]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [152]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [153]:
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [154]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [155]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [135]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [136]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [137]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [138]:
frame2.loc['four']

year       2001
state    Nevada
pop         2.4
debt        NaN
Name: four, dtype: object

In [139]:
frame2['debt'] = 16.0
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.0
two    2001    Ohio  1.7  16.0
three  2002    Ohio  3.6  16.0
four   2001  Nevada  2.4  16.0
five   2002  Nevada  2.9  16.0
six    2003  Nevada  3.2  16.0

In [140]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [141]:
np.arange(1.0,7.0,1) # (초기값, 끝값, 증가값)

array([1., 2., 3., 4., 5., 6.])

In [142]:
frame2['debt'] = np.arange(1.0,13.0,2)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   1.0
two    2001    Ohio  1.7   3.0
three  2002    Ohio  3.6   5.0
four   2001  Nevada  2.4   7.0
five   2002  Nevada  2.9   9.0
six    2003  Nevada  3.2  11.0

In [143]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [144]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [145]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [146]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

#### 행추가

In [198]:
series = pd.Series([2004, "Ohio", 2.9, 13.0], 
                   index=["year",'state','pop','debt'])
frame2.append(series, ignore_index=True,inplace=True)

TypeError: append() got an unexpected keyword argument 'implace'

In [117]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [118]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [107]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [112]:
pop2=pd.DataFrame(pop, index=[2001, 2002, 2003])
pop2

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [111]:
pd.DataFrame(pop)

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [123]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [124]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [125]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [126]:
frame2.values

array([[2000, 'Ohio', 1.5, 1.0],
       [2001, 'Ohio', 1.7, 3.0],
       [2002, 'Ohio', 3.6, 5.0],
       [2001, 'Nevada', 2.4, 7.0],
       [2002, 'Nevada', 2.9, 9.0],
       [2003, 'Nevada', 3.2, 11.0]], dtype=object)

In [182]:
index = ['apple','orange','banana','pear','kiwi']
data1 =[10,5,8,12,3]
data2 =[30,25,12,10,8]
Series1 = pd.Series(data1,index=index)
Series2 = pd.Series(data2,index=index)

In [183]:
Series1

apple     10
orange     5
banana     8
pear      12
kiwi       3
dtype: int64

In [184]:
Series2

apple     30
orange    25
banana    12
pear      10
kiwi       8
dtype: int64

In [185]:
new_column = pd.Series([15,7], index=[0,1])
new_column

0    15
1     7
dtype: int64

In [186]:
df = pd.DataFrame([Series1,Series2])
df

apple  orange  banana  pear  kiwi
0     10       5       8    12     3
1     30      25      12    10     8

In [187]:
df['melon'] = new_column
df

apple  orange  banana  pear  kiwi  melon
0     10       5       8    12     3     15
1     30      25      12    10     8      7

In [188]:
df_T = df.T
df_T

0   1
apple   10  30
orange   5  25
banana   8  12
pear    12  10
kiwi     3   8
melon   15   7

In [205]:
df_T.loc['melon2'] = [1,2]
df_T
df = df_T.T
df

apple  orange  banana  pear  kiwi  melon  melon2
0     10       5       8    12     3     15       1
1     30      25      12    10     8      7       2

### Index Objects

In [206]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index
index[1:]

Index(['b', 'c'], dtype='object')

In [207]:
obj

a    0
b    1
c    2
dtype: int64

index[1] = 'd'  # TypeError

In [208]:
labels = pd.Index(np.arange(3))
labels
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2
obj2.index is labels

True

In [209]:
frame3
frame3.columns
'Ohio' in frame3.columns
2003 in frame3.index

False

In [210]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## Essential Functionality

### Reindexing

In [211]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [212]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [214]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [215]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [226]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [227]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [228]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [235]:
states = ['Texas', 'Utah', 'California']
frame3 = frame.reindex(columns=states)

In [236]:
frame3

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [241]:
frame3.loc[['a', 'c','d'], states]

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### Dropping Entries from an Axis

In [243]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [244]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [245]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [246]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [247]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [253]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [256]:
data.drop('Ohio', axis=0)

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [258]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [259]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [260]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### Indexing, Selection, and Filtering

In [262]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [263]:
obj['b']

1.0

In [264]:
obj[1]

1.0

In [265]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [266]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [267]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [268]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [269]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [270]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [2]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [274]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [275]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [276]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [277]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [278]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [280]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### Selection with loc and iloc

In [3]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [283]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [284]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [285]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [286]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [4]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [288]:
data.loc[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [291]:
data.iloc[:, :3][data.three > 1]

one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

### Integer Indexes

ser = pd.Series(np.arange(3.))
ser
ser[-1]

In [5]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [4]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [5]:
ser2[-1]

2.0

In [6]:
ser[:1]

0    0.0
dtype: float64

In [6]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

이름을 선택할때는 **loc**를  정수색인을 선택할때는  **iloc** : 색인이 1인 곳까지

In [7]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

이름을 선택할때는 **loc**를  정수색인을 선택할때는  **iloc** : 인덱스가 1보다 작은 값(0)까지

In [8]:
ser.iloc[:1]

0    0.0
dtype: float64

### Arithmetic and Data Alignment

In [7]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [8]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [11]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [12]:
list('abcde')

['a', 'b', 'c', 'd', 'e']

In [12]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [13]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [14]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [13]:
df1 = pd.DataFrame({'A': [1, 2]})
df1

A
0  1
1  2

In [14]:
df2 = pd.DataFrame({'B': [3, 4]})
df2

B
0  3
1  4

In [15]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

#### Arithmetic methods with fill values(값 채우기)

In [18]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [26]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [27]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [23]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [19]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [23]:
df1.div(1) # df1 / 1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [24]:
df1.rdiv(1) # 1/df1 : reverse version

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [30]:
df1.reindex(columns=df2.columns)

a    b     c     d   e
0  0.0  1.0   2.0   3.0 NaN
1  4.0  5.0   6.0   7.0 NaN
2  8.0  9.0  10.0  11.0 NaN

In [29]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### Operations between DataFrame and Series

In [31]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [27]:
arr[0]

array([0., 1., 2., 3.])

In [33]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [34]:
arr - arr[1]

array([[-4., -4., -4., -4.],
       [ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.]])

In [35]:
arr - arr[2]

array([[-8., -8., -8., -8.],
       [-4., -4., -4., -4.],
       [ 0.,  0.,  0.,  0.]])

In [37]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [38]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [31]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [32]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [33]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [39]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [41]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [44]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [45]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [46]:
frame.rsub(series3, axis=0)

b    d    e
Utah    1.0  0.0 -1.0
Ohio    1.0  0.0 -1.0
Texas   1.0  0.0 -1.0
Oregon  1.0  0.0 -1.0

### Function Application and Mapping

**np.random.rand()** : 0~1사이의 랜덤 값

In [58]:
np.random.rand()

0.3542538701243291

**np.random.randn()** : 평균0 표준편차1 가우시안 표준정규분포 난수 랜덤

In [57]:
np.random.randn()

-1.2822799819062438

In [68]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.688162  0.150911 -0.450867
Ohio    0.379141 -0.665375  1.386786
Texas  -0.781644 -1.198891  0.701206
Oregon -1.800643 -0.855044  1.430706

In [69]:
np.abs(frame)

b         d         e
Utah    0.688162  0.150911  0.450867
Ohio    0.379141  0.665375  1.386786
Texas   0.781644  1.198891  0.701206
Oregon  1.800643  0.855044  1.430706

In [70]:
f = lambda x: x.max() - x.min()

In [74]:
frame.apply(f, axis=0) # frame.apply(f)

b    2.179784
d    1.349802
e    1.881572
dtype: float64

In [75]:
frame.apply(f, axis='columns') # frame.apply(f, axis=1)

Utah      0.839072
Ohio      2.052162
Texas     1.900097
Oregon    3.231348
dtype: float64

In [76]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -1.800643 -1.198891 -0.450867
max  0.379141  0.150911  1.430706

In [81]:
# format = lambda x: '%.2f' % x
format = lambda x: '{:.2f}'.format(x)
frame.applymap(format)

b      d      e
Utah    -0.69   0.15  -0.45
Ohio     0.38  -0.67   1.39
Texas   -0.78  -1.20   0.70
Oregon  -1.80  -0.86   1.43

In [84]:
frame['e'].map(format)

Utah      -0.45
Ohio       1.39
Texas      0.70
Oregon     1.43
Name: e, dtype: object

### Sorting and Ranking

In [85]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [86]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [87]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [88]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [89]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [91]:
frame.sort_index(axis='columns')

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [95]:
frame.sort_index(axis=0, ascending=False)

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [92]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [96]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [97]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [98]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [99]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [100]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [101]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [104]:
frame.sort_values(by='b', ascending=False)

b  a
1  7  1
0  4  0
3  2  1
2 -3  0

In [112]:
frame.sort_values(by=['a', 'b'], ascending=False)

b  a
1  7  1
3  2  1
0  4  0
2 -3  0

In [111]:
frame.sort_values(by=['a', 'b'], ascending=[False,True])

b  a
3  2  1
1  7  1
2 -3  0
0  4  0

In [129]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [130]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [131]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [132]:
# Assign tie values the maximum rank in the group
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [133]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [137]:
frame.rank(axis='columns') #frame.rank(axis=1)

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [136]:
frame.rank(axis=0) #frame.rank()

b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

### Axis Indexes with Duplicate Labels

In [143]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [144]:
obj.index.is_unique

False

In [147]:
obj2 = pd.Series(range(3), index=['a', 'b', 'c'])
obj2

a    0
b    1
c    2
dtype: int64

In [148]:
obj2.index.is_unique

True

In [149]:
obj['a']

a    0
a    1
dtype: int64

In [150]:
obj['c']

4

In [151]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a  0.984768 -1.044460  0.858333
a  0.927011 -0.237155  0.275909
b -0.552133 -0.406383  0.748586
b -0.001623 -0.796746 -1.182658

In [152]:
df.loc['b']

0         1         2
b -0.552133 -0.406383  0.748586
b -0.001623 -0.796746 -1.182658

## Summarizing and Computing Descriptive Statistics

In [153]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [154]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [155]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [156]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [157]:
df.mean(axis='columns')

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [158]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [159]:
df.idxmax()

one    b
two    d
dtype: object

누적(cumulative) sum

In [160]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [167]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [168]:
df2 = pd.DataFrame([[1., 1.], [2., 1.5],
                   [3., 2.0], [4., 100.0],[5., 9.],[6., 11.]],
                  index=['a', 'b', 'c', 'd','e','f'],
                  columns=['one', 'two'])
df2

one    two
a  1.0    1.0
b  2.0    1.5
c  3.0    2.0
d  4.0  100.0
e  5.0    9.0
f  6.0   11.0

In [169]:
df2.describe()

one         two
count  6.000000    6.000000
mean   3.500000   20.750000
std    1.870829   39.053489
min    1.000000    1.000000
25%    2.250000    1.625000
50%    3.500000    5.500000
75%    4.750000   10.500000
max    6.000000  100.000000

In [170]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [171]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Correlation and Covariance

conda install pandas-datareader

In [ ]:
price = pd.read_pickle('examples/yahoo_price.pkl')
volume = pd.read_pickle('examples/yahoo_volume.pkl')

import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [ ]:
returns = price.pct_change()
returns.tail()

In [ ]:
returns['MSFT'].corr(returns['IBM'])
returns['MSFT'].cov(returns['IBM'])

In [ ]:
returns.MSFT.corr(returns.IBM)

In [ ]:
returns.corr()
returns.cov()

In [ ]:
returns.corrwith(returns.IBM)

In [ ]:
returns.corrwith(volume)

### Unique Values, Value Counts, and Membership

In [173]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [176]:
obj.describe()

count     9
unique    4
top       a
freq      3
dtype: object

In [174]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [175]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [177]:
pd.value_counts(obj.values, sort=False)

d    1
c    3
b    2
a    3
dtype: int64

In [178]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [179]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [180]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [181]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: object

In [182]:
unique_vals = pd.Series(['c', 'b', 'a'])
unique_vals

0    c
1    b
2    a
dtype: object

In [184]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [185]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [190]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

## Conclusion

In [191]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS

NameError: name 'PREVIOUS_MAX_ROWS' is not defined